{% set name = "gcsfuse" %}
{% set version = "2.12.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/GoogleCloudPlatform/gcsfuse/archive/v{{ version }}.tar.gz
  sha256: 500048d3659454ada2d2cad790ec8641dde5ffb2419d040218d7e35f46bce251

build:
  number: 0
  skip: true  # [not linux]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - {{ compiler('go-nocgo') }}
    - go-licenses
  host:
    - libfuse

test:
  commands:
    - gcsfuse --help

about:
  home: https://github.com/GoogleCloudPlatform/gcsfuse
  license: Apache-2.0
  license_file:
    - LICENSE
    - license-files/
  summary: User-space file system for interacting with Google Cloud
  dev_url: https://github.com/GoogleCloudPlatform/gcsfuse

extra:
  recipe-maintainers:
    - danielnachun
