{% set name = "gcsfuse" %}
{% set version = "2.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/GoogleCloudPlatform/gcsfuse/archive/v{{ version }}.tar.gz
  sha256: 9aa48a6d5c5e069ed299b3215095c50859c28af1b60f6598cde7fa847f62c7ce

build:
  number: 0
  skip: true  # [not linux]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - {{ compiler('go-nocgo') }}
    - go-licenses
  host:
    - libfuse

test:
  commands:
    - gcsfuse --help

about:
  home: https://github.com/GoogleCloudPlatform/gcsfuse
  license: Apache-2.0
  license_file:
    - LICENSE
    - license-files/
  summary: User-space file system for interacting with Google Cloud
  dev_url: https://github.com/GoogleCloudPlatform/gcsfuse

extra:
  recipe-maintainers:
    - danielnachun
