{% set name = "gcsfuse" %}
{% set version = "2.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/GoogleCloudPlatform/gcsfuse/archive/v{{ version }}.tar.gz
  sha256: cae13b543e18cdc3af98c726b6009778a4c3980d14535583f5e96bc08defa355

build:
  number: 0
  skip: true  # [not linux]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - {{ compiler('go-nocgo') }}
    - go-licenses
  host:
    - libfuse

test:
  commands:
    - gcsfuse --help

about:
  home: https://github.com/GoogleCloudPlatform/gcsfuse
  license: Apache-2.0
  license_file:
    - LICENSE
    - license-files/
  summary: User-space file system for interacting with Google Cloud
  dev_url: https://github.com/GoogleCloudPlatform/gcsfuse

extra:
  recipe-maintainers:
    - danielnachun
