{% set name = "gcsfuse" %}
{% set version = "2.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/GoogleCloudPlatform/gcsfuse/archive/v{{ version }}.tar.gz
  sha256: bafffcfaabc26bbde71baee3958b812e28f7cbeafaa123a3ef0a0a1836574741

build:
  number: 0
  skip: true  # [not linux]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - {{ compiler('go-nocgo') }}
    - go-licenses
  host:
    - libfuse

test:
  commands:
    - gcsfuse --help

about:
  home: https://github.com/GoogleCloudPlatform/gcsfuse
  license: Apache-2.0
  license_file:
    - LICENSE
    - license-files/
  summary: User-space file system for interacting with Google Cloud
  dev_url: https://github.com/GoogleCloudPlatform/gcsfuse

extra:
  recipe-maintainers:
    - danielnachun
